apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-unidade-deployment
  labels:
    app: api-unidade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-unidade
  template:
    metadata:
      labels:
        app: api-unidade
    spec:
      containers:
        - name: api-unidade
          image: barbearia-unidade:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070
---
apiVersion: v1
kind: Service
metadata:
  name: api-unidade-service
spec:
  type: NodePort
  selector:
    app: api-unidade
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070